### ISSUE TITLE
SLAM not displaying licenses/complaints/healthgrades

### ISSUE THREAD

**Issue by office-cb5** [BetaNYC/SLAM#24]
Hi Beta NYC, 

For some reason, it looks like the license information, complaint data, and health grades are not appearing on SLAM.  

Anything you can advise?  I've got adobe flash working. I don't know what's up

All the best and thank you,
Luke from Community Board Five

**Comment by lindsaypoirier** [comment]
The State Liquor Authority changed two of the column names in their dataset.

doing_business_as_dba was changed to doing_business_as_dba_
and 
actual_address_of_premises_address1 was changed to actual_address_of_premises_address1_

This dataset is set to sync with the BetaNYC Carto account weekly, so when they changed the column name in the dataset and the dataset synced with our Carto account, the SLAM code could no longer recognize our references to those columns. 

I changed all of the references to both of those columns in index.html, and everything worked fine.

**Comment by office-cb5** [comment]
Awesome, thank you so much! The SLA redid their site within the past few
weeks, so I wonder if that had anything to do with it.  Thanks for looking
into it because we use SLAM religiously :)

All the best

*Luke Szabados* | Community Associate | *Community Board Five*
450 Seventh Avenue, #2109 | New York, NY 10123
T: 212-465-0907 | F: 212-465-1628 | luke@cb5.org
